#!/bin/python

with open("example.cimg","wb") as file:
    file.write(b"Cm@g")
    file.write((1).to_bytes(1,"little"))
    file.write((71).to_bytes(1,"little"))
    file.write((21).to_bytes(2,"little"))
    file.write(b"W" * (71*21))
